#!/usr/bin/env python

Import('env')
Import('env_modules')

env_module = env_modules.Clone()
env_module.Append(CPPPATH=[".", "include"])

sources = Glob("*.cpp")
sources += Glob("src/spine/*.c")

# Compile as a static library
lib = env_module.Library("gd_spine", sources)
# Add the library as a dependency of the final executable
env.Prepend(LIBS=[lib])
